---
title: "Untitled"
author: "Krista DeStasio"
date: "3/17/2019"
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float: no
  word_document:
    toc: yes
    toc_depth: '3'
  pdf_document:
    toc: yes
    toc_depth: '3'
---

```{r setup, include=FALSE}
# Clear workspace
rm(list = ls()) 

# Set paths and working directory
working_dir = '~/Dropbox/collaborations/hunter_college/hc_analysis/'
setwd(working_dir)

# Load objects from the clustering analysis
load(paste0(working_dir, 'clustering_objects.Rda'))

list.of.packages <- c('janitor', 'kernlab', 'dplyr', 'ggplot2', 'tidyr', 'knitr', 'cluster', 'mclust', 'flexclust', 'factoextra', 'fpc', 'NbClust')
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])] 
if (length(new.packages)) install.packages(new.packages, repos = "http://cran.us.r-project.org")
lapply(list.of.packages, library, character.only = TRUE)

knitr::opts_chunk$set(fig.width = 12, fig.height = 8, fig.path = 'Figs/', echo = FALSE, eval = TRUE)
```

# k-means
```{r}
# https://www.datanovia.com/en/lessons/cluster-validation-statistics-must-know-methods/

# Internal measures for cluster validation
# (compactness, separation, connectivity)

for (i in 2:3) {
set.seed(50)    
    # K-means clustering
    km_res <- eclust(pca_scaled$x[,1:2], 
                     FUNcluster = 'kmeans', 
                     hc_metric = 'euclidean',
                     k = i, nstart = 25, graph = TRUE)
    
    # Visualization of K-means clustering
   clus_plot <-  fviz_cluster(km_res, geom = 'point', ellipse.type = 'norm', palette = 'jco',
                      print.summary = FALSE,
                      ggtheme = theme_minimal(), 
                      main = paste0("Cluster Plot of K-means With ", i, " Clusters"))
    
    # Silhouette Plot
   sil_plot <- fviz_silhouette(km_res, palette = "jco",
                         print.summary = FALSE) + 
             theme_minimal() + 
             ggtitle(paste0("Silhouette Plot of K-means With ", i, " Clusters"))
    
    # Silhouette information
    silinfo <- km_res$silinfo
    
    df1 <- as.data.frame(cbind(paste0('k-means: ', i, ' clusters'),
        c(1:i), 
        km_res$size, 
        silinfo$clus.avg.widths)) #Average silhouette width of each cluster
    colnames(df1) <- c('Model', 'Cluster', 'Cluster size', 'Average silhouette width')
   
    
    # Statistics for k-means clustering
    km_stats <- cluster.stats(dist(pca_scaled$x[,1:2]),  km_res$cluster)
    # Silhouette width of observation
    sil <- km_res$silinfo$widths[, 1:3]
    # Objects with negative silhouette
    neg_sil_index <- which(sil[, 'sil_width'] < 0)
    
    df2 <- as.data.frame(cbind(paste0('k-means: ', i, ' clusters'),
       silinfo$avg.width, 
       km_stats$average.between,
       km_stats$average.within,
       length(neg_sil_index))) #Average silhouette width of each cluster
    colnames(df2) <- c('Model', 'Average silhouette coefficient', 'Average distance between clusters', 'Average distance within clusters', '# observations with negative silhouette')

    
    # save objects and clean environment
    assign(paste0("km_k", i, '_res'), km_res, envir = globalenv())
    assign(paste0("km_k", i, '_stats'), km_stats, envir = globalenv())
    assign(paste0("km_k", i, '_df_clusstats'), df1, envir = globalenv())
    assign(paste0("km_k", i, '_df_fit'), df2, envir = globalenv())
    assign(paste0("km_k", i, '_clusplot'), clus_plot, envir = globalenv())
    assign(paste0("km_k", i, '_silplot'), sil_plot, envir = globalenv())
    
    rm(km_res, km_stats, sil, silinfo, df1, df2, clus_plot, sil_plot)
}

```

# Hierarchical
```{r}
set.seed(50)
methods <- c("ward.D2", "complete", "average")

for (method in methods) {
    for (i in 2:3) {
        cat(paste0("\n", method, " method: ", i, " clusters\n"))
        # Hierarchical clustering
        hc_res <- eclust(pca_scaled$x[,1:2], 
                         FUNcluster = "hclust", 
                         k = i, 
                         hc_metric = "euclidean", 
                         hc_method = method, graph = TRUE)

        # Visualize dendrograms
        (dendr_plot <- plot(fviz_dend(hc_res, show_labels = FALSE, palette = "jco",
                       rect = TRUE,
                       print.summary = FALSE,
                       as.ggplot = TRUE,
                       main = paste0("Cluster Plot of Hierarchical Clustering With ", method, " Method and ", i, " Centers"))))

        # Visualize clusters
        (clus_plot <- plot(fviz_cluster(hc_res, geom = 'point', ellipse.type = 'norm', palette = 'jco',
                          print.summary = FALSE,
                          ggtheme = theme_minimal(),
                          main = paste0("Cluster Plot of Hierarchical Clustering With ", method, " Method and ", i, " Centers"))))

        # Silhouette Plot
        (sil_plot <- plot(fviz_silhouette(hc_res, palette = "jco",
                             print.summary = FALSE) +
                 theme_minimal() +
                 ggtitle(paste0("Cluster Plot of Hierarchical Clustering With ", method, " Method and ", i, " Centers"))))

        # Silhouette information
        silinfo <- hc_res$silinfo
        df1 <- as.data.frame(cbind(
            paste0('Hierarchical ', method, ' : ', i, ' clusters'),
            c(1:i), 
            hc_res$size, 
            silinfo$clus.avg.widths)) #Average silhouette width of each cluster
        colnames(df1) <- c('Model', 'Cluster', 'Cluster size', 'Average silhouette width')
        
        # Statistics for hierarchical clustering
        hc_stats <- cluster.stats(dist(pca_scaled$x[,1:2]),  hc_res$cluster)
        # Silhouette width of observation
        sil <- hc_res$silinfo$widths[, 1:3]
        # Objects with negative silhouette
        neg_sil_index <- which(sil[, 'sil_width'] < 0)
        
        df2 <- as.data.frame(cbind(
            paste0('Hierarchical ', method, ' : ', i, ' clusters'),
            silinfo$avg.width, 
            hc_stats$average.between,
            hc_stats$average.within,
            length(neg_sil_index))) 
        colnames(df2) <- c('Model', 'Average silhouette coefficient', 'Average distance between clusters', 'Average distance within clusters', '# observations with negative silhouette')
        
        # save objects and clean environment
        assign(paste0("hc_", method, '_k', i), hc_res, envir = globalenv())
        assign(paste0("hc_", method, '_k', i, '_stats'), hc_stats, envir = globalenv())
        assign(paste0('hc_', method, '_k', i, '_clusstats'), df1, envir = globalenv())
        assign(paste0('hc_', method, '_k', i, '_fit'), df2, envir = globalenv())
        assign(paste0('hc_', method, '_k', i, '_clusplot'), clus_plot, envir = globalenv())
        assign(paste0('hc_', method, '_k', i, '_silplot'), sil_plot, envir = globalenv())
        assign(paste0('hc_', method, '_k', i, '_dendrplot'), dendr_plot, envir = globalenv())
        
        rm(hc_res, hc_stats, sil, silinfo, df1, df2)
    }
}
```

# Model comparisons
```{r}
clusstats_df <- do.call(rbind, mget(ls(pattern = "*clusstats")))
clusstats_df$`Average silhouette width` <- as.numeric(as.character(clusstats_df$`Average silhouette width`))
(table_cluster_descr <- kable(clusstats_df, 
      caption = "Cluster Descriptions for K-means", digits = 2, row.names = FALSE))

fit_df <- do.call(rbind, mget(ls(pattern = "*fit")))
varlist <- c("Average silhouette coefficient", "Average distance between clusters", "Average distance within clusters", "# observations with negative silhouette")

fit_df[, varlist] <- sapply(fit_df[varlist], function(x){
   as.numeric(as.character(x))
})
(table_cluster_fit <- kable(fit_df, 
      caption = "Evaluation of Cluster Goodness of Fit for K-means", digits = 2, row.names = FALSE))
```

```{r}
save(table_cluster_descr, table_cluster_fit, fit_df, clusstats_df, file = "descriptives_tables.Rda")
```

